name: Backup repo to Google Drive
 
on:
 push:
   branches:
     - main  # o la rama que uses
 
jobs:
 backup:
   runs-on: ubuntu-latest
 
   steps:
     - name: Checkout repo
       uses: actions/checkout@v4
 
     - name: Install rclone
       run: |
         curl https://rclone.org/install.sh | sudo bash
 
     - name: Create ZIP with timestamp
       run: |
         TIMESTAMP=$(date +"%Y-%m-%d_%H-%M")
         ZIP_NAME="backup-${TIMESTAMP}.zip"
         zip -r "$ZIP_NAME" .
         echo "ZIP_NAME=$ZIP_NAME" >> $GITHUB_ENV
 
     - name: Configure rclone
       env:
         RCLONE_CONFIG: ${{ secrets.RCLONE_CONFIG }}
       run: |
         mkdir -p ~/.config/rclone
         echo -e "$RCLONE_CONFIG" > ~/.config/rclone/rclone.conf
 
     - name: Upload ZIP to Google Drive
       run: |
         rclone copy "$ZIP_NAME" digpathobackend:/BackUps/InteractiveAnotStreamli_HER2 --progress
